#pragma config(Sensor, dgtl1,  touch,          sensorTouch)
#pragma config(Sensor, dgtl2,  encoder,        sensorQuadEncoder)
#pragma config(Motor,  port4,           leftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           rightMotor,    tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*move the base of the robot for a certain amount of time

leftPower -> the power of the motor from -126 (backwards full power)
to 126 (forward full power)

*/
void move(int leftPower, int rightPower, int time)
{
	motor[leftMotor] = leftPower; // set left motor power
	motor[rightMotor] = rightPower; //set right motor power
	wait1Msec(time);
}

task main()
{

	move(126,126,2000);	//move forward for 2 seconds full power

	move(0,0,1000);
	move(60,-60,1000); //spin in place for 1 second

	move(0,0,1000);
	move(0,100,500);	//turn one way for half a second

	//drive forward while the touch sensor is not pressed
	while(SensorValue[touch] == 0)
	{
		move(100,100,0);
		/*
		equivalent to saying
		motor[leftMotor] = 100;
		motor[rightMotor] = 100;
		*/
	}
	while(SensorValue[encoder] < 1000)
	{

	}
	move(0,0,1000);
}
